#include "filesystem.h"
#include <root_directory.h> // This is a configuration file generated by CMake.
#include <cstdlib>

std::string const& FileSystem::getRoot()
{
#ifdef NDEBUG
	static std::string root = "";
#else
	static std::string envRoot = []() {
	#ifdef _MSC_VER
		char* buffer = nullptr;
		size_t length = 0;
		if (_dupenv_s(&buffer, &length, "LOGL_ROOT_PATH") != 0 || buffer == nullptr) {
			return std::string();
		}
		std::string value(buffer);
		free(buffer);
		return value;
	#else
		const char* value = std::getenv("LOGL_ROOT_PATH");
		return value != nullptr ? std::string(value) : std::string();
	#endif
	}();
	static char const* givenRoot = (!envRoot.empty() ? envRoot.c_str() : logl_root);
	static std::string root = (givenRoot != nullptr ? givenRoot : "");
#endif
	return root;
}
